# fly.toml file generated for t1000-server on 2023-03-26T09:53:13-04:00

app = "t1000-server"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "yul"
processes = []

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
